### ISSUE TITLE
Cant Compile Script

### ISSUE THREAD

**Issue by ImBeefy** [RedFalconKen/RedFalconFlightSystem-Heliz#9]
Seems all your discord links are broken?
Whenver i try to load your helicopter mod together with the Codelock mod. It gives me all kinds of errors.
Im trying to install it on an Expansion server aswell. Dont know if that plays a role.

**Comment by RedFalconKen** [comment]
Here's a valid Discord link: 
https://discord.gg/redfalcon-modz-850263994966736926

Going to need a lot more diagnostics (logs and such) to see what's going on and where they may be a conflict (likely not Codelock)

**Comment by ImBeefy** [comment]
My apologies. This was user error, i deleted mod, reinstalled it and now theres no errors.
Thanks for the link and quick reply. !
